style(ci): enhance error reporting for unformatted Go files

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -71,4 +71,11 @@ jobs:
           } >> "$GITHUB_ENV"
 
       - name: Check formatting of Go files
-        run: test -z "$UNFORMATTED_FILES"
+        run: >
+          test -z "$UNFORMATTED_FILES" || {
+            echo "$UNFORMATTED_FILES" | while read -r filename
+            do
+                echo "::error file=$filename::Missing gofmt"
+            done
+            exit 1
+          }
